[build]
   base = "client/"
   publish = "dist/"
   command = "npm run build"

[build.environment]
   NODE_VERSION = "18.18.0"

[[redirects]]
  from = "/api/*"
  to = "https://project-management-tool-jj3f.onrender.com/api:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
